name: Update rugby feeds

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: {}     # allow manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run update

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update fixtures and results"
          file_pattern: "fixtures.json results.json"
